version: '3.7'

services:
  nest-db:
    image: postgres:11
    container_name: nest-db
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./tmp/nest-db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-box-solution
  nest-back:
    build: ../../back
    container_name: nest-back
    restart: always
    depends_on:
      - nest-db
    ports:
      - "3000:3000"
    environment:
      - APPLICATION_PORT=3000
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=nest-box-solution
    volumes:
      - ../scripts/wait-for-it.sh:/wait-for-it.sh


